### ISSUE TITLE
cant get infinite feature with angular click function working.

### ISSUE THREAD

**Issue by TiesTheunissen** [GreenFlag31/carousel-library#3]
Hi GreenFlag31,

while using your library i've attached the default angular click function on my items with the infinite feature. but after the original items that are in the carousel the click function doesnt work anymore. only on the original items. when the infinite feature is active (so the second time for the first items the (click) breaks.
here is the code:

            <carousel class="carousel"
                [dots]="true"
                [arrows]="false"
                [counter]="false" 
                [slideToShow]="3"
                [infinite]="true" 
                [animationTimingFn]="'ease-in-out'" 
                [autoSlide]="true"
                [autoPlay]="true"
                [autoPlayAtStart]="true"
                [responsive]="false">
                @for(company of projects; track company) {

                <div class="project carousel-slide" (click)="selectLogo(company)">
                    <img [src]="company.logo"  />
                </div>
                }
            </carousel>

**Comment by GreenFlag31** [comment]
Sure, because once you have surpassed the initial set of slides, new cloned slides will be added: 
```javascript
        const clonedElement = this.arrayOfSlides[i].cloneNode(true);
        this.slidesContainer.append(clonedElement);
```
those cloned slides won't contain any event or directive that you have attached to them.

Things that come to my mind: 
* Dynamically adding the click event on new slides created (I don't think this is even possible within the Angular API)
* Extending the carousel API to add a click event (javascript, not angular API) on new slides created.

I think (no research done for now) that only the second option is possible.

**Comment by TiesTheunissen** [comment]
i'll try the 3th option then. thnx! if there is an option in the future available to have this integrated that would be awesome.

**Comment by GreenFlag31** [comment]
Actually I think that the second option and the third are very similar, since even if I add this possibility within the API and trigger an (for example) RxJs subject when a slide is clicked, you will still have to perform a check to see which target it is. So not really a great added value. Only the first option would add value, but I don't believe this is possible.

**Comment by TiesTheunissen** [comment]
if i've got some time left i can take a look at the library myself and make a pull request if i have a sulution available what ofc is robust. still thnx for everything!

**Comment by GreenFlag31** [comment]
Yep, feel free to take a look at it. I have realised that this is indeed a problem, because if the content of the carousel is translated (translate pipe for example), the translation will be lost, which is of course a problem. I don't believe there is currently an Angular way to achieve this.

I have opened a new request feature on Github: https://github.com/angular/angular/issues/54660
